
import { Geist, Geist_Mono } from "next/font/google";
import { Metadata } from "next";
import "./globals.css";

// Google fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: {
    template: "%s | ACP",
    default: "ACP",
  },
  description: "Generated by create next app...............",
};

// Root layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="min-h-screen">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <header className="bg-gray-200 p-4">
          <h2>Header</h2>
        </header> */}

        <main className="flex-1">{children}</main>

        {/* <footer className="bg-gray-200 p-4">
          <h2>Footer</h2>
        </footer> */}
      </body>
    </html>
  );
}
