
import "./globals.css";  // tailwind first
import "bootstrap/dist/css/bootstrap.min.css"; // then bootstrap
// import "bootstrap/dist/js/bootstrap.bundle.min.js";

import { type Metadata } from "next";
import { ClerkProvider, } from "@clerk/nextjs";
import ReduxProviderClient from "@/store/providers/ReduxProviderClient";



// Metadata
export const metadata: Metadata = {
  title: {
    template: "%s | ACP",
    default: "ACP",
  },
  description: "Generated by create next app...............",
};

// Root layout
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en" className="min-h-screen">
        <body className=" text-black  " style={{ backgroundColor: "#f6fff6" }}>
          <ReduxProviderClient>
            {children}
          </ReduxProviderClient>
        </body>
      </html>
    </ClerkProvider>
  );
}
